### ISSUE TITLE
Commits of 1.2.1 release missing in this repos?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zc.lockfile#10]
On [PyPI](https://pypi.python.org/pypi/zc.lockfile/1.2.1) there is a 1.2.1 release of this package which seems to be missing in the repository. (See [CHANGES.txt](https://github.com/zopefoundation/zc.lockfile/blob/master/CHANGES.txt) and [Releases](https://github.com/zopefoundation/zc.lockfile/releases).)

@jimfulton and @strichter: You are the only ones who are allowed to release to PyPI. Does the one who did the release still have the commits laying around to push them to the repos?

**Comment by jimfulton** [comment]
Sorry, my bad, I forgot to push, as I often do. :( Pushed.

**Comment by mgedmin** [comment]
@jimfulton have you considered using zest.releaser for making releases?  It automates all the release steps, including the git push (with manual confirmations for every command it runs so you can trust it's not doing anything stupid or unexpected).
