### ISSUE TITLE
Release 1.4

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zc.lockfile#18]
The only persons with PyPI rights are @jimfulton and @strichter.
Can one of you please cut a release or give me (`icemac`) the necessary rights to do so?

**Comment by jimfulton** [comment]
You are now worthy!

:)

Thanks!

Jim

**Comment by icemac** [comment]
Thank you @jimfulton! Released as https://pypi.org/project/zc.lockfile/1.4/
