### ISSUE TITLE
Setuptools should not be a runtime dep

### ISSUE THREAD

**Issue by pombredanne** [zopefoundation/zc.lockfile#22]
https://github.com/zopefoundation/zc.lockfile/blame/2e9545afb4141d60d707a25f28f66d33a74e7fe5/setup.py#L51 is a tad weird ... I do not think this is needed.

**Comment by jamadden** [comment]
But it is. setuptools provides `pkg_resources` and `pkg_resources` is used in the `__init__.py` of this package (and every other `zc.*` package) to handle namespaces.

https://github.com/zopefoundation/zc.lockfile/blob/2e9545afb4141d60d707a25f28f66d33a74e7fe5/src/zc/__init__.py#L1

**Comment by pombredanne** [comment]
@jamadden true, I forgot about that!
Thanks!

**Comment by pombredanne** [comment]
I guess it would be nice to adopt native namespace packages from Python 3.6+ ?

**Comment by mgedmin** [comment]
> I guess it would be nice to adopt native namespace packages from Python 3.6+ ?

That would involve more than one package, so perhaps it would be best to discuss that in https://github.com/zopefoundation/meta/issues.
