### ISSUE TITLE
Add ability to include the hostname in lockfile in addition to the PID

### ISSUE THREAD

**Issue by akaihola** [zopefoundation/zc.lockfile#6]
In a container environment (e.g. Docker), the PID is typically always identical even if multiple containers are running under the same operating system instance.

Clearly, inspecting lock files doesn't then help much in debugging. It would be very useful to be able to identify the container which created the lock file. Since Docker uses the container identifier or name as the hostname, this information can be stored in the lock file in addition to or instead of the PID.

**Comment by pombredanne** [comment]
@akaihola is this ready for a PR?

**Comment by akaihola** [comment]
This was actually merged in #7 and included in the 1.2.0 release. I probably messed up the GitHub workflow somehow. Thanks for the heads up!

**Comment by jimfulton** [comment]
@akaihola we want to stop logging when we can't acquire a lock. Will that hurt any of your use cases?  We'll continue to format the lockfile as you implemented.
